WebServer/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GroupCheck.WebServer
{
	public class SharedController : Controller
	{
		//[OutputCache(Duration = 3600, VaryByCustom = "testCustom", VaryByParam ="id")]
		//[ChildActionOnly]
		public ActionResult ZhopaPartial(List<string> test)
		{
			return PartialView((object)DateTime.Now.ToString("HH:mm:ss"));
			// return Json(token.Encode(), JsonRequestBehavior.AllowGet);
		}
	}
}

WebServer/Views/Shared/ZhopaPartial.cshtml
@model string
@{
	Layout = null;

}
@Model

<div id="appEditor">
	<div>
		First Name:
		<input type="text" v-model="user.firstName" :disabled="!isEditing"
			   :class="{view: !isEditing}">
		<input type="text" v-model="user.xName" v-on:click="alert('aa');">
	</div><div>
		Last Name:
		<input type="text" v-model="user.lastName" :disabled="!isEditing"
			   class="view">
	</div>
	<button @@click="isEditing = !isEditing" v-if="!isEditing">Edit</button>
	<button @@click="save" v-else-if="isEditing">Save</button>
	<button v-if="isEditing" @@click="cancel">Cancel</button>

</div>
<style>
	.view {
		border-color: transparent;
		background-color: initial;
		color: initial
	}
	.view:enabled {
		border-color: #f00;
		background-color: initial;
		color: initial
	}
</style>
<script>
	var app = new Vue({
		el: '#appEditor',
		data: {
			isEditing: false,
			user: {
				firstName: 'John',
				xName: '',
				lastName: 'Smith',
			}
		},
		mounted() {
			this.cachedUser = Object.assign({}, this.user);
		},
		methods: {
			save() {
				this.cachedUser = Object.assign({}, this.user);
				this.isEditing = false;
			},
			cancel() {
				this.user = Object.assign({}, this.cachedUser);
				this.isEditing = false;
			}
		}
	})
</script>

WebServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>@ViewBag.Title</title>
	<link href="~/Content/site.css" rel="stylesheet" type="text/css" />
	<script src="~/Scripts/vue.min.js"></script>
	<script src="~/Scripts/vue-router.min.js"></script>
</head>
<body>
	@Html.Action("ZhopaPartial", "Shared");
	@RenderBody()
</body>
</html>